Import-Module "$env:ProgramData\chocolatey\helpers\chocolateyInstaller.psm1"
$APPSFOLDER="C:\Apps"

Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\Audacity.lnk" -TargetPath "$APPSFOLDER\Audacity\audacity.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\Avidemux.lnk" -TargetPath "$APPSFOLDER\AvidemuxPortable\AvidemuxPortable.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\CPU-Z.lnk" -TargetPath "$APPSFOLDER\CPU-Z\cpuz_x64.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\CrystalDiskInfo.lnk" -TargetPath "$APPSFOLDER\CrystalDiskInfo\DiskInfoX64.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\CrystalDiskMark.lnk" -TargetPath "$APPSFOLDER\CrystalDiskMark\DiskMark64.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\HWiNFO.lnk" -TargetPath "$APPSFOLDER\HWiNFO\HWiNFO64.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\CheckFlash.lnk" -TargetPath "$APPSFOLDER\CheckFlash\ChkFlsh.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\KeePass.lnk" -TargetPath "$APPSFOLDER\KeePass\KeePass.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\MKVtoolnix-MKVextract.lnk" -TargetPath "$APPSFOLDER\MKVtoolnix-MKVextract\mkvinfo-gui.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\MPC-HC.lnk" -TargetPath "$APPSFOLDER\MPC-HC\mpc-hc64.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\MSI Afterburner.lnk" -TargetPath "$APPSFOLDER\MSI Afterburner\MSIAfterburner.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\OBS.lnk" -TargetPath "$APPSFOLDER\OBS\OBS.exe" -Arguments "-portable"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\PicPick.lnk" -TargetPath "$APPSFOLDER\picpick\picpick.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\Recuva.lnk" -TargetPath "$APPSFOLDER\recuva\recuva.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\Speccy.lnk" -TargetPath "$APPSFOLDER\speccy\Speccy64.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\VirtualDub.lnk" -TargetPath "$APPSFOLDER\VirtualDub\Veedub64.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\WinDirStatPortable.lnk" -TargetPath "$APPSFOLDER\WinDirStatPortable\WinDirStatPortable.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\WinSCP.lnk" -TargetPath "$APPSFOLDER\WinSCP\WinSCP.exe"
Install-ChocolateyShortcut -ShortcutFilePath "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Portable\Wireshark.lnk" -TargetPath "$APPSFOLDER\WiresharkPortable\WiresharkPortable.exe"
